"""Re-export hub for storage access symbols used across the memory facade.

Sibling implementation slices historically reach storage and repository
functions through the package facade (``_memory_api.<name>``).  Keeping those
imports in one explicit module preserves every facade symbol while letting
focused modules own their implementations.  Callers should progressively
migrate to importing directly from ``storage`` / ``storage.repositories``.
"""

from __future__ import annotations

from typing import Any  # noqa: F401  (re-exported for facade consumers)

from novelforge.core.schemas import (
    ArcOutlineMetadata,
    ChapterOutlineMetadata,
    ConflictResolution,
    CreativeAttachment,
    CreativeFragment,
    CreativeProfile,
    CreativeSession,
    CreativeSessionBundle,
    CreativeTurn,
    StoryMeta,
    VolumeOutlineMetadata,
)
from novelforge.core.prompt_options import normalize_prompt_options_payload
from storage import (
    initialize_global_db,
    initialize_project_db,
    inspect_global_db,
    inspect_project_db,
    open_existing_project_db,
    open_global_db,
    open_project_db,
)
from storage.repositories import (
    claim_next_source_ingestion_task_row,
    claim_source_ingestion_task_row,
    cleanup_archived_source_ingestion_task_rows,
    append_retrieval_feedback_row,
    begin_creative_turn_row,
    complete_creative_turn_row,
    create_creative_session_row,
    delete_creative_session_row,
    delete_knowledge_category_item,
    delete_pending_knowledge_items,
    delete_workflow_run_snapshot,
    delete_archived_source_ingestion_task_row,
    fail_creative_turn_row,
    finalize_creative_session_rows,
    get_project_meta,
    load_global_setting,
    load_asset_payload,
    load_creative_fragment_row,
    load_creative_session_row,
    load_entity_alias_group_rows,
    load_auto_review_policy_row,
    load_auto_review_run_rows,
    load_conflict_resolution_rows,
    load_prompt_options_payload,
    load_rules_payload,
    load_story_profile_row,
    load_knowledge_category_rows,
    load_pending_knowledge_rows,
    load_retrieval_eval_case_rows,
    load_retrieval_eval_run_rows,
    load_retrieval_feedback_rows,
    load_retrieval_manifest_payload,
    load_retrieval_vector_store_payload,
    list_asset_file_rows,
    list_asset_payload_rows,
    list_creative_fragment_rows,
    list_creative_work_rows,
    list_creative_session_rows,
    list_creative_turn_rows,
    list_retrieval_source_file_rows,
    load_long_reference_batch_row,
    load_long_reference_batch_rows,
    list_workflow_run_ids,
    list_workflow_run_summaries,
    list_source_ingestion_task_rows,
    load_workflow_run_snapshot,
    load_source_ingestion_task_control_row,
    load_source_ingestion_task_row,
    list_story_rows,
    clone_story_storage_rows,
    purge_story_scoped_rows,
    project_maintenance_mode,
    rename_project_meta,
    mark_asset_deleted,
    mark_long_reference_batch_deleted,
    mark_retrieval_source_file_deleted,
    register_asset_file,
    sync_auto_review_policy,
    sync_auto_review_runs,
    sync_conflict_resolution,
    sync_global_setting,
    sync_prompt_options_payload,
    sync_rules_payload,
    sync_story_profile,
    sync_entity_alias_groups,
    sync_knowledge_category,
    sync_pending_knowledge,
    sync_long_reference_batch,
    sync_retrieval_source_file,
    sync_retrieval_eval_cases,
    sync_retrieval_eval_run,
    sync_retrieval_manifest_payload,
    sync_retrieval_vector_store_payload,
    sync_stories_index,
    sync_workflow_run_snapshot,
    heartbeat_source_ingestion_task_row,
    release_source_ingestion_task_lease_row,
    request_source_ingestion_task_control_row,
    set_source_ingestion_task_archived_row,
    set_project_maintenance_mode,
    settle_stale_source_ingestion_controls_row,
    sync_source_ingestion_task_row,
    upsert_asset_payload,
    upsert_knowledge_category_item,
    upsert_pending_knowledge_items,
    upsert_project_meta,
    update_creative_fragment_row,
    update_creative_session_row,
    list_creative_attachment_rows,
    list_all_creative_attachment_rows,
    claim_turn_creative_attachment_rows,
    load_creative_attachment_row,
    release_turn_creative_attachment_rows,
    update_creative_attachment_row,
    upsert_creative_attachment_row,
    claim_creative_action_row,
    insert_creative_action_row,
    insert_creative_config_revision_row,
    insert_creative_message_row,
    list_creative_action_rows,
    list_creative_message_rows,
    load_creative_action_row,
    load_creative_config_revision_row,
    mark_creative_config_revision_reversed_row,
    transition_creative_action_row,
    update_creative_action_row,
)
